In [2]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import numpy as np

In [3]:
train = pd.read_csv('train.csv', parse_dates=['Day.Index'], dayfirst=True)
test = pd.read_csv('test.csv', parse_dates=['Day.Index'], dayfirst=True)
ss = pd.read_csv('samplesubmission.csv')

In [4]:
#Extracting Day, month, weekday, year from Date

In [1]:
train['Day.Index'] = pd.to_datetime(train['Day.Index'], format='%y-%m-%d')
test['Day.Index'] = pd.to_datetime(test['Day.Index'], format='%y-%m-%d')

train['Year'] = train['Day.Index'].dt.year
train['Month'] = train['Day.Index'].dt.month
train['Week'] = train['Day.Index'].dt.week
train['Day_Of_Week'] = train['Day.Index'].dt.dayofweek
train['Day'] = train['Day.Index'].dt.day
train['Day_Of_Year'] = train['Day.Index'].dt.dayofyear

test['Year'] = test['Day.Index'].dt.year
test['Month'] = test['Day.Index'].dt.month
test['Week'] = test['Day.Index'].dt.week
test['Day_Of_Week'] = test['Day.Index'].dt.dayofweek
test['Day'] = test['Day.Index'].dt.day
test['Day_Of_Year'] = test['Day.Index'].dt.dayofyear

In [ ]:
#Checking Null values

In [5]:
train.isnull().any()

test.isnull().any()

Day.Index           False
Campaign            False
Impressions         False
Target.Clicks       False
Obt.Click           False
Min.CPC             False
Max.CPC             False
CTR                 False
Amount.Spend        False
Returning.Users     False
Targeted.Leads      False
SpecialDay          False
Avg. Bounce.Rate    False
Avg.Time.Page       False
Avg.Position        False
Total.Revenue       False
dtype: bool

In [ ]:
data = train.append(test, ignore_index=True)
data['Obtained.Leads'].fillna(0, inplace=True)

In [ ]:
test.shape

In [ ]:
30*14

In [ ]:
# data.isnull().any()

In [ ]:
def function1(X):
    return int(round(X["Amount.Spend"]/X["Obt.Click"]))

In [5]:
data["CPC"]=data.apply(function1,axis=1)
train["CPC"]=train.apply(function1,axis=1)
test["CPC"]=test.apply(function1,axis=1)

In [ ]:
train.to_csv("modified_train.csv",index=False)
test.to_csv("modified_test.csv",index=False)
data.to_csv('modified_data.csv',index=False)

In [7]:
train.head()

,Day.Index,Campaign,Impressions,Target.Clicks,Obt.Click,Min.CPC,Max.CPC,CTR,Amount.Spend,Returning.Users,Targeted.Leads,SpecialDay,Avg. Bounce.Rate,Avg.Time.Page,Avg.Position,Total.Revenue,Obtained.Leads
0,1/1/2013,1,13930,225,200,28,31,1.44,6200,36,15,1,70.81,571,5,2401,20
1,2/1/2013,1,11177,225,288,28,31,2.58,8352,27,20,0,32.38,447,3,4033,18
2,3/1/2013,1,12968,225,211,28,31,1.63,5908,31,14,0,99.01,322,1,4637,13
3,4/1/2013,1,13850,225,238,28,31,1.72,6664,38,16,0,43.60,534,2,3597,26
4,5/1/2013,1,12346,225,259,28,31,2.10,7511,41,18,0,23.24,481,8,1923,18

In [25]:
train.head(20)

,Day.Index,Campaign,Impressions,Target.Clicks,Obt.Click,Min.CPC,Max.CPC,CTR,Amount.Spend,Returning.Users,Targeted.Leads,SpecialDay,Avg. Bounce.Rate,Avg.Time.Page,Avg.Position,Total.Revenue,Obtained.Leads,no,Delete
0,1/1/2013,1,13930,225,200,28,31,1.44,6200,36,15,1,70.81,571,5,2401,20,0,0
1,2/1/2013,1,11177,225,288,28,31,2.58,8352,27,20,0,32.38,447,3,4033,18,1,1
2,3/1/2013,1,12968,225,211,28,31,1.63,5908,31,14,0,99.01,322,1,4637,13,2,2
3,4/1/2013,1,13850,225,238,28,31,1.72,6664,38,16,0,43.60,534,2,3597,26,3,3
4,5/1/2013,1,12346,225,259,28,31,2.10,7511,41,18,0,23.24,481,8,1923,18,4,4
5,6/1/2013,1,11694,225,208,28,31,1.78,6448,35,16,0,57.43,549,8,2573,14,5,5
6,7/1/2013,1,14100,225,178,28,31,1.26,5518,26,13,0,0.68,522,3,4974,18,6,6
7,8/1/2013,1,10513,225,101,28,31,0.96,2828,36,7,0,2.98,373,2,4800,8,7,0
8,9/1/2013,1,13040,225,213,28,31,1.63,6390,36,15,0,96.02,484,2,4698,20,8,1
9,10/1/2013,1,14719,225,208,28,31,1.41,6032,25,15,0,17.11,392,1,2880,16,9,2
10,11/1/2013,1,11665,225,155,28,31,1.33,4650,27,11,0,4.80,211,8,2215,5,10,3
11,12/1/2013,1,10553,225,270,28,31,2.56,7560,22,18,0,45.99,396,7,1234,12,11,4
12,13-01-2013,1,11559,225,206,28,31,1.78,5974,33,14,0,7.75,373,4,4434,10,12,5
13,14-01-2013,1,11365,225,237,28,31,2.09,6873,22,17,0,85.27,305,2,4517,7,13,6
14,15-01-2013,1,12965,225,285,28,31,2.20,7980,35,19,0,97.95,372,5,1017,13,14,0
15,16-01-2013,1,10852,225,281,28,31,2.59,8149,45,20,0,94.34,576,5,3438,18,15,1
16,17-01-2013,1,10477,225,126,28,31,1.20,3528,38,8,0,15.12,382,5,2898,10,16,2
17,18-01-2013,1,14836,225,182,28,31,1.23,5642,28,14,0,96.31,379,7,2231,11,17,3
18,19-01-2013,1,13538,225,143,28,31,1.06,4290,36,10,0,91.02,249,2,4951,12,18,4
19,20-01-2013,1,13276,225,218,28,31,1.64,6758,40,16,0,36.43,214,6,1719,17,19,5

In [20]:
train["no"]=train.index

In [22]:
def func(X):
    return (X["no"]%7)

In [23]:
train["Delete"]=train.apply(func,axis=1)

In [ ]:
#no